package tech.housemoran.realgood.models.protobuf;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/Inmate.proto

public final class InmateData {
	private InmateData() {}
	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}
	public interface InmateOrBuilder extends
			// @@protoc_insertion_point(interface_extends:Inmate)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>required string name = 1;</code>
		 */
		boolean hasName();
		/**
		 * <code>required string name = 1;</code>
		 */
		java.lang.String getName();
		/**
		 * <code>required string name = 1;</code>
		 */
		com.google.protobuf.ByteString
		getNameBytes();

		/**
		 * <code>required string jail = 2;</code>
		 */
		boolean hasJail();
		/**
		 * <code>required string jail = 2;</code>
		 */
		java.lang.String getJail();
		/**
		 * <code>required string jail = 2;</code>
		 */
		com.google.protobuf.ByteString
		getJailBytes();

		/**
		 * <code>required string date = 3;</code>
		 */
		boolean hasDate();
		/**
		 * <code>required string date = 3;</code>
		 */
		java.lang.String getDate();
		/**
		 * <code>required string date = 3;</code>
		 */
		com.google.protobuf.ByteString
		getDateBytes();

		/**
		 * <code>required string bail = 5;</code>
		 */
		boolean hasBail();
		/**
		 * <code>required string bail = 5;</code>
		 */
		java.lang.String getBail();
		/**
		 * <code>required string bail = 5;</code>
		 */
		com.google.protobuf.ByteString
		getBailBytes();

		/**
		 * <code>required string age = 6;</code>
		 */
		boolean hasAge();
		/**
		 * <code>required string age = 6;</code>
		 */
		java.lang.String getAge();
		/**
		 * <code>required string age = 6;</code>
		 */
		com.google.protobuf.ByteString
		getAgeBytes();

		/**
		 * <code>optional .Inmate.Gender gender = 7;</code>
		 */
		boolean hasGender();
		/**
		 * <code>optional .Inmate.Gender gender = 7;</code>
		 */
		tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender getGender();

		/**
		 * <code>optional string releaseable = 8;</code>
		 */
		boolean hasReleaseable();
		/**
		 * <code>optional string releaseable = 8;</code>
		 */
		java.lang.String getReleaseable();
		/**
		 * <code>optional string releaseable = 8;</code>
		 */
		com.google.protobuf.ByteString
		getReleaseableBytes();

		/**
		 * <code>optional string mug_shot = 9;</code>
		 */
		boolean hasMugShot();
		/**
		 * <code>optional string mug_shot = 9;</code>
		 */
		java.lang.String getMugShot();
		/**
		 * <code>optional string mug_shot = 9;</code>
		 */
		com.google.protobuf.ByteString
		getMugShotBytes();

		/**
		 * <code>optional string race = 10;</code>
		 */
		boolean hasRace();
		/**
		 * <code>optional string race = 10;</code>
		 */
		java.lang.String getRace();
		/**
		 * <code>optional string race = 10;</code>
		 */
		com.google.protobuf.ByteString
		getRaceBytes();

		/**
		 * <code>required string bookingDescription = 4;</code>
		 */
		boolean hasBookingDescription();
		/**
		 * <code>required string bookingDescription = 4;</code>
		 */
		java.lang.String getBookingDescription();
		/**
		 * <code>required string bookingDescription = 4;</code>
		 */
		com.google.protobuf.ByteString
		getBookingDescriptionBytes();
	}
	/**
	 * Protobuf type {@code Inmate}
	 */
	public static final class Inmate extends
			com.google.protobuf.GeneratedMessage implements
			// @@protoc_insertion_point(message_implements:Inmate)
			InmateOrBuilder {
		// Use Inmate.newBuilder() to construct.
		private Inmate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}
		private Inmate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

		private static final Inmate defaultInstance;
		public static Inmate getDefaultInstance() {
			return defaultInstance;
		}

		public Inmate getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;
		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}
		private Inmate(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownField(input, unknownFields,
									extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000001;
							name_ = bs;
							break;
						}
						case 18: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000002;
							jail_ = bs;
							break;
						}
						case 26: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000004;
							date_ = bs;
							break;
						}
						case 34: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000200;
							bookingDescription_ = bs;
							break;
						}
						case 42: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000008;
							bail_ = bs;
							break;
						}
						case 50: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000010;
							age_ = bs;
							break;
						}
						case 56: {
							int rawValue = input.readEnum();
							tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender value = tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender.valueOf(rawValue);
							if (value == null) {
								unknownFields.mergeVarintField(7, rawValue);
							} else {
								bitField0_ |= 0x00000020;
								gender_ = value;
							}
							break;
						}
						case 66: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000040;
							releaseable_ = bs;
							break;
						}
						case 74: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000080;
							mugShot_ = bs;
							break;
						}
						case 82: {
							com.google.protobuf.ByteString bs = input.readBytes();
							bitField0_ |= 0x00000100;
							race_ = bs;
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}
		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return tech.housemoran.realgood.models.protobuf.InmateData.internal_static_Inmate_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return tech.housemoran.realgood.models.protobuf.InmateData.internal_static_Inmate_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							tech.housemoran.realgood.models.protobuf.InmateData.Inmate.class, tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Builder.class);
		}

		public static com.google.protobuf.Parser<Inmate> PARSER =
				new com.google.protobuf.AbstractParser<Inmate>() {
					public Inmate parsePartialFrom(
							com.google.protobuf.CodedInputStream input,
							com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
						return new Inmate(input, extensionRegistry);
					}
				};

		@java.lang.Override
		public com.google.protobuf.Parser<Inmate> getParserForType() {
			return PARSER;
		}

		/**
		 * Protobuf enum {@code Inmate.Gender}
		 */
		public enum Gender
				implements com.google.protobuf.ProtocolMessageEnum {
			/**
			 * <code>MALE = 0;</code>
			 */
			MALE(0, 0),
			/**
			 * <code>FEMALE = 1;</code>
			 */
			FEMALE(1, 1),
			/**
			 * <code>UNKNOWN = 2;</code>
			 */
			UNKNOWN(2, 2),
			;

			/**
			 * <code>MALE = 0;</code>
			 */
			public static final int MALE_VALUE = 0;
			/**
			 * <code>FEMALE = 1;</code>
			 */
			public static final int FEMALE_VALUE = 1;
			/**
			 * <code>UNKNOWN = 2;</code>
			 */
			public static final int UNKNOWN_VALUE = 2;


			public final int getNumber() { return value; }

			public static Gender valueOf(int value) {
				switch (value) {
					case 0: return MALE;
					case 1: return FEMALE;
					case 2: return UNKNOWN;
					default: return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<Gender>
			internalGetValueMap() {
				return internalValueMap;
			}
			private static com.google.protobuf.Internal.EnumLiteMap<Gender>
					internalValueMap =
					new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
						public Gender findValueByNumber(int number) {
							return Gender.valueOf(number);
						}
					};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor
			getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}
			public final com.google.protobuf.Descriptors.EnumDescriptor
			getDescriptorForType() {
				return getDescriptor();
			}
			public static final com.google.protobuf.Descriptors.EnumDescriptor
			getDescriptor() {
				return tech.housemoran.realgood.models.protobuf.InmateData.Inmate.getDescriptor().getEnumTypes().get(0);
			}

			private static final Gender[] VALUES = values();

			public static Gender valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}

			private final int index;
			private final int value;

			private Gender(int index, int value) {
				this.index = index;
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:Inmate.Gender)
		}

		private int bitField0_;
		public static final int NAME_FIELD_NUMBER = 1;
		private java.lang.Object name_;
		/**
		 * <code>required string name = 1;</code>
		 */
		public boolean hasName() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		/**
		 * <code>required string name = 1;</code>
		 */
		public java.lang.String getName() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					name_ = s;
				}
				return s;
			}
		}
		/**
		 * <code>required string name = 1;</code>
		 */
		public com.google.protobuf.ByteString
		getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int JAIL_FIELD_NUMBER = 2;
		private java.lang.Object jail_;
		/**
		 * <code>required string jail = 2;</code>
		 */
		public boolean hasJail() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}
		/**
		 * <code>required string jail = 2;</code>
		 */
		public java.lang.String getJail() {
			java.lang.Object ref = jail_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					jail_ = s;
				}
				return s;
			}
		}
		/**
		 * <code>required string jail = 2;</code>
		 */
		public com.google.protobuf.ByteString
		getJailBytes() {
			java.lang.Object ref = jail_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(java.lang.String) ref);
				jail_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int DATE_FIELD_NUMBER = 3;
		private java.lang.Object date_;
		/**
		 * <code>required string date = 3;</code>
		 */
		public boolean hasDate() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}
		/**
		 * <code>required string date = 3;</code>
		 */
		public java.lang.String getDate() {
			java.lang.Object ref = date_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					date_ = s;
				}
				return s;
			}
		}
		/**
		 * <code>required string date = 3;</code>
		 */
		public com.google.protobuf.ByteString
		getDateBytes() {
			java.lang.Object ref = date_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(java.lang.String) ref);
				date_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int BAIL_FIELD_NUMBER = 5;
		private java.lang.Object bail_;
		/**
		 * <code>required string bail = 5;</code>
		 */
		public boolean hasBail() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}
		/**
		 * <code>required string bail = 5;</code>
		 */
		public java.lang.String getBail() {
			java.lang.Object ref = bail_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					bail_ = s;
				}
				return s;
			}
		}
		/**
		 * <code>required string bail = 5;</code>
		 */
		public com.google.protobuf.ByteString
		getBailBytes() {
			java.lang.Object ref = bail_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(java.lang.String) ref);
				bail_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int AGE_FIELD_NUMBER = 6;
		private java.lang.Object age_;
		/**
		 * <code>required string age = 6;</code>
		 */
		public boolean hasAge() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}
		/**
		 * <code>required string age = 6;</code>
		 */
		public java.lang.String getAge() {
			java.lang.Object ref = age_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					age_ = s;
				}
				return s;
			}
		}
		/**
		 * <code>required string age = 6;</code>
		 */
		public com.google.protobuf.ByteString
		getAgeBytes() {
			java.lang.Object ref = age_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(java.lang.String) ref);
				age_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int GENDER_FIELD_NUMBER = 7;
		private tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender gender_;
		/**
		 * <code>optional .Inmate.Gender gender = 7;</code>
		 */
		public boolean hasGender() {
			return ((bitField0_ & 0x00000020) == 0x00000020);
		}
		/**
		 * <code>optional .Inmate.Gender gender = 7;</code>
		 */
		public tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender getGender() {
			return gender_;
		}

		public static final int RELEASEABLE_FIELD_NUMBER = 8;
		private java.lang.Object releaseable_;
		/**
		 * <code>optional string releaseable = 8;</code>
		 */
		public boolean hasReleaseable() {
			return ((bitField0_ & 0x00000040) == 0x00000040);
		}
		/**
		 * <code>optional string releaseable = 8;</code>
		 */
		public java.lang.String getReleaseable() {
			java.lang.Object ref = releaseable_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					releaseable_ = s;
				}
				return s;
			}
		}
		/**
		 * <code>optional string releaseable = 8;</code>
		 */
		public com.google.protobuf.ByteString
		getReleaseableBytes() {
			java.lang.Object ref = releaseable_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(java.lang.String) ref);
				releaseable_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int MUG_SHOT_FIELD_NUMBER = 9;
		private java.lang.Object mugShot_;
		/**
		 * <code>optional string mug_shot = 9;</code>
		 */
		public boolean hasMugShot() {
			return ((bitField0_ & 0x00000080) == 0x00000080);
		}
		/**
		 * <code>optional string mug_shot = 9;</code>
		 */
		public java.lang.String getMugShot() {
			java.lang.Object ref = mugShot_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					mugShot_ = s;
				}
				return s;
			}
		}
		/**
		 * <code>optional string mug_shot = 9;</code>
		 */
		public com.google.protobuf.ByteString
		getMugShotBytes() {
			java.lang.Object ref = mugShot_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(java.lang.String) ref);
				mugShot_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int RACE_FIELD_NUMBER = 10;
		private java.lang.Object race_;
		/**
		 * <code>optional string race = 10;</code>
		 */
		public boolean hasRace() {
			return ((bitField0_ & 0x00000100) == 0x00000100);
		}
		/**
		 * <code>optional string race = 10;</code>
		 */
		public java.lang.String getRace() {
			java.lang.Object ref = race_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					race_ = s;
				}
				return s;
			}
		}
		/**
		 * <code>optional string race = 10;</code>
		 */
		public com.google.protobuf.ByteString
		getRaceBytes() {
			java.lang.Object ref = race_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(java.lang.String) ref);
				race_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int BOOKINGDESCRIPTION_FIELD_NUMBER = 4;
		private java.lang.Object bookingDescription_;
		/**
		 * <code>required string bookingDescription = 4;</code>
		 */
		public boolean hasBookingDescription() {
			return ((bitField0_ & 0x00000200) == 0x00000200);
		}
		/**
		 * <code>required string bookingDescription = 4;</code>
		 */
		public java.lang.String getBookingDescription() {
			java.lang.Object ref = bookingDescription_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					bookingDescription_ = s;
				}
				return s;
			}
		}
		/**
		 * <code>required string bookingDescription = 4;</code>
		 */
		public com.google.protobuf.ByteString
		getBookingDescriptionBytes() {
			java.lang.Object ref = bookingDescription_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(java.lang.String) ref);
				bookingDescription_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			name_ = "";
			jail_ = "";
			date_ = "";
			bail_ = "";
			age_ = "";
			gender_ = tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender.MALE;
			releaseable_ = "";
			mugShot_ = "";
			race_ = "";
			bookingDescription_ = "";
		}
		private byte memoizedIsInitialized = -1;
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			if (!hasName()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasJail()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasDate()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasBail()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasAge()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasBookingDescription()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getNameBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getJailBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getDateBytes());
			}
			if (((bitField0_ & 0x00000200) == 0x00000200)) {
				output.writeBytes(4, getBookingDescriptionBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBytes(5, getBailBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeBytes(6, getAgeBytes());
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				output.writeEnum(7, gender_.getNumber());
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				output.writeBytes(8, getReleaseableBytes());
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				output.writeBytes(9, getMugShotBytes());
			}
			if (((bitField0_ & 0x00000100) == 0x00000100)) {
				output.writeBytes(10, getRaceBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, getNameBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(2, getJailBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(3, getDateBytes());
			}
			if (((bitField0_ & 0x00000200) == 0x00000200)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(4, getBookingDescriptionBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(5, getBailBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(6, getAgeBytes());
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				size += com.google.protobuf.CodedOutputStream
						.computeEnumSize(7, gender_.getNumber());
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(8, getReleaseableBytes());
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(9, getMugShotBytes());
			}
			if (((bitField0_ & 0x00000100) == 0x00000100)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(10, getRaceBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static tech.housemoran.realgood.models.protobuf.InmateData.Inmate parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static tech.housemoran.realgood.models.protobuf.InmateData.Inmate parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static tech.housemoran.realgood.models.protobuf.InmateData.Inmate parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static tech.housemoran.realgood.models.protobuf.InmateData.Inmate parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static tech.housemoran.realgood.models.protobuf.InmateData.Inmate parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}
		public static tech.housemoran.realgood.models.protobuf.InmateData.Inmate parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}
		public static tech.housemoran.realgood.models.protobuf.InmateData.Inmate parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}
		public static tech.housemoran.realgood.models.protobuf.InmateData.Inmate parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}
		public static tech.housemoran.realgood.models.protobuf.InmateData.Inmate parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}
		public static tech.housemoran.realgood.models.protobuf.InmateData.Inmate parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() { return Builder.create(); }
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(tech.housemoran.realgood.models.protobuf.InmateData.Inmate prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		public Builder toBuilder() { return newBuilder(this); }

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		/**
		 * Protobuf type {@code Inmate}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:Inmate)
				tech.housemoran.realgood.models.protobuf.InmateData.InmateOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return tech.housemoran.realgood.models.protobuf.InmateData.internal_static_Inmate_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return tech.housemoran.realgood.models.protobuf.InmateData.internal_static_Inmate_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								tech.housemoran.realgood.models.protobuf.InmateData.Inmate.class, tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Builder.class);
			}

			// Construct using tech.housemoran.realgood.models.protobuf.InmateData.Inmate.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}
			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}
			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				name_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				jail_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				date_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				bail_ = "";
				bitField0_ = (bitField0_ & ~0x00000008);
				age_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				gender_ = tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender.MALE;
				bitField0_ = (bitField0_ & ~0x00000020);
				releaseable_ = "";
				bitField0_ = (bitField0_ & ~0x00000040);
				mugShot_ = "";
				bitField0_ = (bitField0_ & ~0x00000080);
				race_ = "";
				bitField0_ = (bitField0_ & ~0x00000100);
				bookingDescription_ = "";
				bitField0_ = (bitField0_ & ~0x00000200);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return tech.housemoran.realgood.models.protobuf.InmateData.internal_static_Inmate_descriptor;
			}

			public tech.housemoran.realgood.models.protobuf.InmateData.Inmate getDefaultInstanceForType() {
				return tech.housemoran.realgood.models.protobuf.InmateData.Inmate.getDefaultInstance();
			}

			public tech.housemoran.realgood.models.protobuf.InmateData.Inmate build() {
				tech.housemoran.realgood.models.protobuf.InmateData.Inmate result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public tech.housemoran.realgood.models.protobuf.InmateData.Inmate buildPartial() {
				tech.housemoran.realgood.models.protobuf.InmateData.Inmate result = new tech.housemoran.realgood.models.protobuf.InmateData.Inmate(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.name_ = name_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.jail_ = jail_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.date_ = date_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.bail_ = bail_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.age_ = age_;
				if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
					to_bitField0_ |= 0x00000020;
				}
				result.gender_ = gender_;
				if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
					to_bitField0_ |= 0x00000040;
				}
				result.releaseable_ = releaseable_;
				if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
					to_bitField0_ |= 0x00000080;
				}
				result.mugShot_ = mugShot_;
				if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
					to_bitField0_ |= 0x00000100;
				}
				result.race_ = race_;
				if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
					to_bitField0_ |= 0x00000200;
				}
				result.bookingDescription_ = bookingDescription_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof tech.housemoran.realgood.models.protobuf.InmateData.Inmate) {
					return mergeFrom((tech.housemoran.realgood.models.protobuf.InmateData.Inmate)other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(tech.housemoran.realgood.models.protobuf.InmateData.Inmate other) {
				if (other == tech.housemoran.realgood.models.protobuf.InmateData.Inmate.getDefaultInstance()) return this;
				if (other.hasName()) {
					bitField0_ |= 0x00000001;
					name_ = other.name_;
					onChanged();
				}
				if (other.hasJail()) {
					bitField0_ |= 0x00000002;
					jail_ = other.jail_;
					onChanged();
				}
				if (other.hasDate()) {
					bitField0_ |= 0x00000004;
					date_ = other.date_;
					onChanged();
				}
				if (other.hasBail()) {
					bitField0_ |= 0x00000008;
					bail_ = other.bail_;
					onChanged();
				}
				if (other.hasAge()) {
					bitField0_ |= 0x00000010;
					age_ = other.age_;
					onChanged();
				}
				if (other.hasGender()) {
					setGender(other.getGender());
				}
				if (other.hasReleaseable()) {
					bitField0_ |= 0x00000040;
					releaseable_ = other.releaseable_;
					onChanged();
				}
				if (other.hasMugShot()) {
					bitField0_ |= 0x00000080;
					mugShot_ = other.mugShot_;
					onChanged();
				}
				if (other.hasRace()) {
					bitField0_ |= 0x00000100;
					race_ = other.race_;
					onChanged();
				}
				if (other.hasBookingDescription()) {
					bitField0_ |= 0x00000200;
					bookingDescription_ = other.bookingDescription_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasName()) {

					return false;
				}
				if (!hasJail()) {

					return false;
				}
				if (!hasDate()) {

					return false;
				}
				if (!hasBail()) {

					return false;
				}
				if (!hasAge()) {

					return false;
				}
				if (!hasBookingDescription()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				tech.housemoran.realgood.models.protobuf.InmateData.Inmate parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (tech.housemoran.realgood.models.protobuf.InmateData.Inmate) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}
			private int bitField0_;

			private java.lang.Object name_ = "";
			/**
			 * <code>required string name = 1;</code>
			 */
			public boolean hasName() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			/**
			 * <code>required string name = 1;</code>
			 */
			public java.lang.String getName() {
				java.lang.Object ref = name_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						name_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>required string name = 1;</code>
			 */
			public com.google.protobuf.ByteString
			getNameBytes() {
				java.lang.Object ref = name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>required string name = 1;</code>
			 */
			public Builder setName(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				name_ = value;
				onChanged();
				return this;
			}
			/**
			 * <code>required string name = 1;</code>
			 */
			public Builder clearName() {
				bitField0_ = (bitField0_ & ~0x00000001);
				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}
			/**
			 * <code>required string name = 1;</code>
			 */
			public Builder setNameBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				name_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object jail_ = "";
			/**
			 * <code>required string jail = 2;</code>
			 */
			public boolean hasJail() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}
			/**
			 * <code>required string jail = 2;</code>
			 */
			public java.lang.String getJail() {
				java.lang.Object ref = jail_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						jail_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>required string jail = 2;</code>
			 */
			public com.google.protobuf.ByteString
			getJailBytes() {
				java.lang.Object ref = jail_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					jail_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>required string jail = 2;</code>
			 */
			public Builder setJail(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				jail_ = value;
				onChanged();
				return this;
			}
			/**
			 * <code>required string jail = 2;</code>
			 */
			public Builder clearJail() {
				bitField0_ = (bitField0_ & ~0x00000002);
				jail_ = getDefaultInstance().getJail();
				onChanged();
				return this;
			}
			/**
			 * <code>required string jail = 2;</code>
			 */
			public Builder setJailBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				jail_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object date_ = "";
			/**
			 * <code>required string date = 3;</code>
			 */
			public boolean hasDate() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}
			/**
			 * <code>required string date = 3;</code>
			 */
			public java.lang.String getDate() {
				java.lang.Object ref = date_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						date_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>required string date = 3;</code>
			 */
			public com.google.protobuf.ByteString
			getDateBytes() {
				java.lang.Object ref = date_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					date_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>required string date = 3;</code>
			 */
			public Builder setDate(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				date_ = value;
				onChanged();
				return this;
			}
			/**
			 * <code>required string date = 3;</code>
			 */
			public Builder clearDate() {
				bitField0_ = (bitField0_ & ~0x00000004);
				date_ = getDefaultInstance().getDate();
				onChanged();
				return this;
			}
			/**
			 * <code>required string date = 3;</code>
			 */
			public Builder setDateBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				date_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object bail_ = "";
			/**
			 * <code>required string bail = 5;</code>
			 */
			public boolean hasBail() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}
			/**
			 * <code>required string bail = 5;</code>
			 */
			public java.lang.String getBail() {
				java.lang.Object ref = bail_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						bail_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>required string bail = 5;</code>
			 */
			public com.google.protobuf.ByteString
			getBailBytes() {
				java.lang.Object ref = bail_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					bail_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>required string bail = 5;</code>
			 */
			public Builder setBail(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				bail_ = value;
				onChanged();
				return this;
			}
			/**
			 * <code>required string bail = 5;</code>
			 */
			public Builder clearBail() {
				bitField0_ = (bitField0_ & ~0x00000008);
				bail_ = getDefaultInstance().getBail();
				onChanged();
				return this;
			}
			/**
			 * <code>required string bail = 5;</code>
			 */
			public Builder setBailBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				bail_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object age_ = "";
			/**
			 * <code>required string age = 6;</code>
			 */
			public boolean hasAge() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}
			/**
			 * <code>required string age = 6;</code>
			 */
			public java.lang.String getAge() {
				java.lang.Object ref = age_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						age_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>required string age = 6;</code>
			 */
			public com.google.protobuf.ByteString
			getAgeBytes() {
				java.lang.Object ref = age_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					age_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>required string age = 6;</code>
			 */
			public Builder setAge(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				age_ = value;
				onChanged();
				return this;
			}
			/**
			 * <code>required string age = 6;</code>
			 */
			public Builder clearAge() {
				bitField0_ = (bitField0_ & ~0x00000010);
				age_ = getDefaultInstance().getAge();
				onChanged();
				return this;
			}
			/**
			 * <code>required string age = 6;</code>
			 */
			public Builder setAgeBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				age_ = value;
				onChanged();
				return this;
			}

			private tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender gender_ = tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender.MALE;
			/**
			 * <code>optional .Inmate.Gender gender = 7;</code>
			 */
			public boolean hasGender() {
				return ((bitField0_ & 0x00000020) == 0x00000020);
			}
			/**
			 * <code>optional .Inmate.Gender gender = 7;</code>
			 */
			public tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender getGender() {
				return gender_;
			}
			/**
			 * <code>optional .Inmate.Gender gender = 7;</code>
			 */
			public Builder setGender(tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000020;
				gender_ = value;
				onChanged();
				return this;
			}
			/**
			 * <code>optional .Inmate.Gender gender = 7;</code>
			 */
			public Builder clearGender() {
				bitField0_ = (bitField0_ & ~0x00000020);
				gender_ = tech.housemoran.realgood.models.protobuf.InmateData.Inmate.Gender.MALE;
				onChanged();
				return this;
			}

			private java.lang.Object releaseable_ = "";
			/**
			 * <code>optional string releaseable = 8;</code>
			 */
			public boolean hasReleaseable() {
				return ((bitField0_ & 0x00000040) == 0x00000040);
			}
			/**
			 * <code>optional string releaseable = 8;</code>
			 */
			public java.lang.String getReleaseable() {
				java.lang.Object ref = releaseable_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						releaseable_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>optional string releaseable = 8;</code>
			 */
			public com.google.protobuf.ByteString
			getReleaseableBytes() {
				java.lang.Object ref = releaseable_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					releaseable_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>optional string releaseable = 8;</code>
			 */
			public Builder setReleaseable(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000040;
				releaseable_ = value;
				onChanged();
				return this;
			}
			/**
			 * <code>optional string releaseable = 8;</code>
			 */
			public Builder clearReleaseable() {
				bitField0_ = (bitField0_ & ~0x00000040);
				releaseable_ = getDefaultInstance().getReleaseable();
				onChanged();
				return this;
			}
			/**
			 * <code>optional string releaseable = 8;</code>
			 */
			public Builder setReleaseableBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000040;
				releaseable_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object mugShot_ = "";
			/**
			 * <code>optional string mug_shot = 9;</code>
			 */
			public boolean hasMugShot() {
				return ((bitField0_ & 0x00000080) == 0x00000080);
			}
			/**
			 * <code>optional string mug_shot = 9;</code>
			 */
			public java.lang.String getMugShot() {
				java.lang.Object ref = mugShot_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						mugShot_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>optional string mug_shot = 9;</code>
			 */
			public com.google.protobuf.ByteString
			getMugShotBytes() {
				java.lang.Object ref = mugShot_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					mugShot_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>optional string mug_shot = 9;</code>
			 */
			public Builder setMugShot(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000080;
				mugShot_ = value;
				onChanged();
				return this;
			}
			/**
			 * <code>optional string mug_shot = 9;</code>
			 */
			public Builder clearMugShot() {
				bitField0_ = (bitField0_ & ~0x00000080);
				mugShot_ = getDefaultInstance().getMugShot();
				onChanged();
				return this;
			}
			/**
			 * <code>optional string mug_shot = 9;</code>
			 */
			public Builder setMugShotBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000080;
				mugShot_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object race_ = "";
			/**
			 * <code>optional string race = 10;</code>
			 */
			public boolean hasRace() {
				return ((bitField0_ & 0x00000100) == 0x00000100);
			}
			/**
			 * <code>optional string race = 10;</code>
			 */
			public java.lang.String getRace() {
				java.lang.Object ref = race_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						race_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>optional string race = 10;</code>
			 */
			public com.google.protobuf.ByteString
			getRaceBytes() {
				java.lang.Object ref = race_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					race_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>optional string race = 10;</code>
			 */
			public Builder setRace(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000100;
				race_ = value;
				onChanged();
				return this;
			}
			/**
			 * <code>optional string race = 10;</code>
			 */
			public Builder clearRace() {
				bitField0_ = (bitField0_ & ~0x00000100);
				race_ = getDefaultInstance().getRace();
				onChanged();
				return this;
			}
			/**
			 * <code>optional string race = 10;</code>
			 */
			public Builder setRaceBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000100;
				race_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object bookingDescription_ = "";
			/**
			 * <code>required string bookingDescription = 4;</code>
			 */
			public boolean hasBookingDescription() {
				return ((bitField0_ & 0x00000200) == 0x00000200);
			}
			/**
			 * <code>required string bookingDescription = 4;</code>
			 */
			public java.lang.String getBookingDescription() {
				java.lang.Object ref = bookingDescription_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						bookingDescription_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>required string bookingDescription = 4;</code>
			 */
			public com.google.protobuf.ByteString
			getBookingDescriptionBytes() {
				java.lang.Object ref = bookingDescription_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(java.lang.String) ref);
					bookingDescription_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>required string bookingDescription = 4;</code>
			 */
			public Builder setBookingDescription(
					java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000200;
				bookingDescription_ = value;
				onChanged();
				return this;
			}
			/**
			 * <code>required string bookingDescription = 4;</code>
			 */
			public Builder clearBookingDescription() {
				bitField0_ = (bitField0_ & ~0x00000200);
				bookingDescription_ = getDefaultInstance().getBookingDescription();
				onChanged();
				return this;
			}
			/**
			 * <code>required string bookingDescription = 4;</code>
			 */
			public Builder setBookingDescriptionBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000200;
				bookingDescription_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:Inmate)
		}

		static {
			defaultInstance = new Inmate(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:Inmate)
	}

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_Inmate_descriptor;
	private static
	com.google.protobuf.GeneratedMessage.FieldAccessorTable
			internal_static_Inmate_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}
	private static com.google.protobuf.Descriptors.FileDescriptor
			descriptor;
	static {
		java.lang.String[] descriptorData = {
				"\n\036src/main/protobuf/Inmate.proto\"\353\001\n\006Inm" +
						"ate\022\014\n\004name\030\001 \002(\t\022\014\n\004jail\030\002 \002(\t\022\014\n\004date\030" +
						"\003 \002(\t\022\014\n\004bail\030\005 \002(\t\022\013\n\003age\030\006 \002(\t\022\036\n\006gend" +
						"er\030\007 \001(\0162\016.Inmate.Gender\022\023\n\013releaseable\030" +
						"\010 \001(\t\022\020\n\010mug_shot\030\t \001(\t\022\014\n\004race\030\n \001(\t\022\032\n" +
						"\022bookingDescription\030\004 \002(\t\"+\n\006Gender\022\010\n\004M" +
						"ALE\020\000\022\n\n\006FEMALE\020\001\022\013\n\007UNKNOWN\020\002B$\n\026tech.h" +
						"ousemoran.modelsB\nInmateData"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {
						}, assigner);
		internal_static_Inmate_descriptor =
				getDescriptor().getMessageTypes().get(0);
		internal_static_Inmate_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_Inmate_descriptor,
				new java.lang.String[] { "Name", "Jail", "Date", "Bail", "Age", "Gender", "Releaseable", "MugShot", "Race", "BookingDescription", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}